// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/cert": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "查询证书信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "证书信息"
                ],
                "summary": "查询证书信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "条件",
                        "name": "condition",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页数",
                        "name": "pageNum",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "总数  由服务器返回回去",
                        "name": "total",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code: 200 成功",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    },
                    "500": {
                        "description": "错误返回内容",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "修改证书信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "证书信息"
                ],
                "summary": "修改证书信息",
                "parameters": [
                    {
                        "description": "修改证书信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/repository.ModifyCert"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code: 200 成功",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    },
                    "500": {
                        "description": "错误返回内容",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "创建证书信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "证书信息"
                ],
                "summary": "创建证书信息",
                "parameters": [
                    {
                        "description": "创建证书信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/repository.CreateCert"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code: 200 成功",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    },
                    "500": {
                        "description": "错误返回内容",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "删除证书信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "证书信息"
                ],
                "summary": "删除证书信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code: 200 成功",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    },
                    "500": {
                        "description": "错误返回内容",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    }
                }
            }
        },
        "/api/v1/cert/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "通过编码查询证书信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "证书信息"
                ],
                "summary": "通过编码查询证书信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "证书信息编码",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code: 200 成功",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    },
                    "500": {
                        "description": "错误返回内容",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    }
                }
            }
        },
        "/api/v1/node": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "查询节点信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "节点信息"
                ],
                "summary": "查询节点信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "条件",
                        "name": "condition",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页数",
                        "name": "pageNum",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "端口信息编码",
                        "name": "portId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "总数  由服务器返回回去",
                        "name": "total",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code: 200 成功",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    },
                    "500": {
                        "description": "错误返回内容",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "修改节点信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "节点信息"
                ],
                "summary": "修改节点信息",
                "parameters": [
                    {
                        "description": "修改节点信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/repository.ModifyNode"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code: 200 成功",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    },
                    "500": {
                        "description": "错误返回内容",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "创建节点信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "节点信息"
                ],
                "summary": "创建节点信息",
                "parameters": [
                    {
                        "description": "创建节点信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/repository.CreateNode"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code: 200 成功",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    },
                    "500": {
                        "description": "错误返回内容",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "删除节点信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "节点信息"
                ],
                "summary": "删除节点信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code: 200 成功",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    },
                    "500": {
                        "description": "错误返回内容",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    }
                }
            }
        },
        "/api/v1/node/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "通过编码查询节点信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "节点信息"
                ],
                "summary": "通过编码查询节点信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "节点信息编码",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code: 200 成功",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    },
                    "500": {
                        "description": "错误返回内容",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    }
                }
            }
        },
        "/api/v1/port": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "查询端口信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "端口信息"
                ],
                "summary": "查询端口信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "条件",
                        "name": "condition",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页数",
                        "name": "pageNum",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "总数  由服务器返回回去",
                        "name": "total",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code: 200 成功",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    },
                    "500": {
                        "description": "错误返回内容",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "修改端口信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "端口信息"
                ],
                "summary": "修改端口信息",
                "parameters": [
                    {
                        "description": "修改端口信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/repository.ModifyPort"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code: 200 成功",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    },
                    "500": {
                        "description": "错误返回内容",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "创建端口信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "端口信息"
                ],
                "summary": "创建端口信息",
                "parameters": [
                    {
                        "description": "创建端口信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/repository.CreatePort"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code: 200 成功",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    },
                    "500": {
                        "description": "错误返回内容",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "删除端口信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "端口信息"
                ],
                "summary": "删除端口信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code: 200 成功",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    },
                    "500": {
                        "description": "错误返回内容",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    }
                }
            }
        },
        "/api/v1/port/reload/{id}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "重启端口对应的服务",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "端口信息"
                ],
                "summary": "重启端口对应的服务",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code: 200 成功",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    },
                    "500": {
                        "description": "错误返回内容",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    }
                }
            }
        },
        "/api/v1/port/state/{id}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "修改端口使用状态",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "端口信息"
                ],
                "summary": "修改端口使用状态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code: 200 成功",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    },
                    "500": {
                        "description": "错误返回内容",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    }
                }
            }
        },
        "/api/v1/port/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "通过编码查询端口信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "端口信息"
                ],
                "summary": "通过编码查询端口信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "端口信息编码",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code: 200 成功",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    },
                    "500": {
                        "description": "错误返回内容",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    }
                }
            }
        },
        "/api/v1/rule": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "查询匹配规则信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "匹配规则信息"
                ],
                "summary": "查询匹配规则信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "条件",
                        "name": "condition",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "节点编码",
                        "name": "nodeId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页数",
                        "name": "pageNum",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "端口编码",
                        "name": "portId",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "总数  由服务器返回回去",
                        "name": "total",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code: 200 成功",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    },
                    "500": {
                        "description": "错误返回内容",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "修改匹配规则信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "匹配规则信息"
                ],
                "summary": "修改匹配规则信息",
                "parameters": [
                    {
                        "description": "修改匹配规则信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/repository.ModifyRule"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code: 200 成功",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    },
                    "500": {
                        "description": "错误返回内容",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "创建匹配规则信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "匹配规则信息"
                ],
                "summary": "创建匹配规则信息",
                "parameters": [
                    {
                        "description": "创建匹配规则信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/repository.CreateRule"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code: 200 成功",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    },
                    "500": {
                        "description": "错误返回内容",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "删除匹配规则信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "匹配规则信息"
                ],
                "summary": "删除匹配规则信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code: 200 成功",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    },
                    "500": {
                        "description": "错误返回内容",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    }
                }
            }
        },
        "/api/v1/rule/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "通过编码查询匹配规则信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "匹配规则信息"
                ],
                "summary": "通过编码查询匹配规则信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "匹配规则信息编码",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code: 200 成功",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    },
                    "500": {
                        "description": "错误返回内容",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    }
                }
            }
        },
        "/api/v1/target": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "查询目标地址信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "目标地址信息"
                ],
                "summary": "查询目标地址信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "条件",
                        "name": "condition",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页数",
                        "name": "pageNum",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "页码",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "总数  由服务器返回回去",
                        "name": "total",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code: 200 成功",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    },
                    "500": {
                        "description": "错误返回内容",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "修改目标地址信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "目标地址信息"
                ],
                "summary": "修改目标地址信息",
                "parameters": [
                    {
                        "description": "修改目标地址信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/repository.ModifyTarget"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code: 200 成功",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    },
                    "500": {
                        "description": "错误返回内容",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "创建目标地址信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "目标地址信息"
                ],
                "summary": "创建目标地址信息",
                "parameters": [
                    {
                        "description": "创建目标地址信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/repository.CreateTarget"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code: 200 成功",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    },
                    "500": {
                        "description": "错误返回内容",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "删除目标地址信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "目标地址信息"
                ],
                "summary": "删除目标地址信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code: 200 成功",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    },
                    "500": {
                        "description": "错误返回内容",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    }
                }
            }
        },
        "/api/v1/target/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "通过编码查询目标地址信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "目标地址信息"
                ],
                "summary": "通过编码查询目标地址信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "目标地址信息编码",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code: 200 成功",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    },
                    "500": {
                        "description": "错误返回内容",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    }
                }
            }
        },
        "/api/v1/user": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "添加用户信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户信息管理"
                ],
                "summary": "添加用户信息",
                "parameters": [
                    {
                        "description": "添加用户信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/repository.CreateUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code: 200 成功",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    },
                    "500": {
                        "description": "错误返回内容",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    }
                }
            }
        },
        "/api/v1/user/state/{id}": {
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "修改用户状态",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户信息管理"
                ],
                "summary": "修改用户状态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code: 200 成功",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    },
                    "500": {
                        "description": "错误返回内容",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    }
                }
            }
        },
        "/api/v1/user/{id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取定时任务列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户信息管理"
                ],
                "summary": "获取定时任务列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code: 200 成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controller.Full"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.User"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "错误返回内容",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "修改用户信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户信息管理"
                ],
                "summary": "修改用户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "修改用户信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/repository.ModifyUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code: 200 成功",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    },
                    "500": {
                        "description": "错误返回内容",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "删除用户信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户信息管理"
                ],
                "summary": "删除用户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code: 200 成功",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    },
                    "500": {
                        "description": "错误返回内容",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    }
                }
            }
        },
        "/api/v1/users": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "获取定时任务列表",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户信息管理"
                ],
                "summary": "获取定时任务列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "uid 登录名",
                        "name": "account",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "备注",
                        "name": "mark",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "用户姓名",
                        "name": "name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code: 200 成功",
                        "schema": {
                            "$ref": "#/definitions/controller.Full"
                        }
                    },
                    "500": {
                        "description": "错误返回内容",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "` + "`" + `` + "`" + `` + "`" + `\n用户登录\n` + "`" + `` + "`" + `` + "`" + `",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "基本接口"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录信息",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/repository.Login"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.Full"
                        }
                    },
                    "500": {
                        "description": "错误返回内容",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    }
                }
            }
        },
        "/logout": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "用户登出时，调用此接口",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "基本接口"
                ],
                "summary": "用户登出",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    },
                    "500": {
                        "description": "错误返回内容",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    }
                }
            }
        },
        "/refreshToken": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "当token即将获取或者过期时刷新token",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "基本接口"
                ],
                "summary": "刷新token",
                "responses": {
                    "200": {
                        "description": "code:200 成功",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controller.Full"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/middleware.JwtToken"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "错误返回内容",
                        "schema": {
                            "$ref": "#/definitions/controller.Base"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.Base": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "状态码",
                    "type": "integer"
                },
                "message": {
                    "description": "状态消息",
                    "type": "string"
                },
                "requestDatetime": {
                    "description": "请求时间",
                    "type": "string"
                },
                "requestId": {
                    "description": "请求ID",
                    "type": "string"
                },
                "responseDatetime": {
                    "description": "返回时间",
                    "type": "string"
                }
            }
        },
        "controller.Full": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "状态码",
                    "type": "integer"
                },
                "data": {
                    "description": "返回数据"
                },
                "message": {
                    "description": "状态消息",
                    "type": "string"
                },
                "requestDatetime": {
                    "description": "请求时间",
                    "type": "string"
                },
                "requestId": {
                    "description": "请求ID",
                    "type": "string"
                },
                "responseDatetime": {
                    "description": "返回时间",
                    "type": "string"
                }
            }
        },
        "middleware.JwtToken": {
            "type": "object",
            "properties": {
                "expires": {
                    "description": "时间",
                    "type": "string"
                },
                "id": {
                    "description": "id",
                    "type": "integer"
                },
                "name": {
                    "description": "用户名",
                    "type": "string"
                },
                "token": {
                    "description": "token",
                    "type": "string"
                },
                "uid": {
                    "description": "用户ID",
                    "type": "string"
                }
            }
        },
        "model.User": {
            "type": "object",
            "properties": {
                "account": {
                    "description": "uid 登录名",
                    "type": "string"
                },
                "id": {
                    "description": "编码",
                    "type": "integer"
                },
                "mark": {
                    "description": "备注",
                    "type": "string"
                },
                "name": {
                    "description": "用户姓名",
                    "type": "string"
                },
                "password": {
                    "description": "密码",
                    "type": "string"
                },
                "state": {
                    "description": "状态 0 停用 1 启用",
                    "type": "integer"
                }
            }
        },
        "repository.CreateCert": {
            "type": "object",
            "required": [
                "name",
                "private",
                "public"
            ],
            "properties": {
                "mark": {
                    "description": "备注",
                    "type": "string"
                },
                "name": {
                    "description": "名称",
                    "type": "string"
                },
                "private": {
                    "description": "私有证书路径",
                    "type": "string"
                },
                "public": {
                    "description": "公有证书路径",
                    "type": "string"
                }
            }
        },
        "repository.CreateNode": {
            "type": "object",
            "required": [
                "name",
                "portId",
                "target"
            ],
            "properties": {
                "mark": {
                    "description": "备注",
                    "type": "string"
                },
                "name": {
                    "description": "匹配路由名称",
                    "type": "string"
                },
                "nodeType": {
                    "description": "节点类型 0 api 1 页面",
                    "type": "integer"
                },
                "pagePath": {
                    "description": "静态页面存放路径 注：相对路径，由服务对页面进行管理",
                    "type": "string"
                },
                "portId": {
                    "description": "端口信息编码",
                    "type": "string"
                },
                "target": {
                    "description": "目标服务地址",
                    "type": "string"
                }
            }
        },
        "repository.CreatePort": {
            "type": "object",
            "required": [
                "port"
            ],
            "properties": {
                "certId": {
                    "description": "证书编码",
                    "type": "string"
                },
                "isTLS": {
                    "description": "是否证书加密",
                    "type": "boolean"
                },
                "mark": {
                    "description": "备注",
                    "type": "string"
                },
                "port": {
                    "description": "端口号",
                    "type": "integer"
                }
            }
        },
        "repository.CreateRule": {
            "type": "object",
            "required": [
                "name",
                "portId",
                "target"
            ],
            "properties": {
                "mark": {
                    "description": "备注",
                    "type": "string"
                },
                "matchType": {
                    "description": "匹配模式 0 所有内容匹配 1 正则匹配 2 包含匹配 3 header 匹配",
                    "type": "integer"
                },
                "name": {
                    "description": "匹配路由名称",
                    "type": "string"
                },
                "nodeId": {
                    "description": "节点信息编码",
                    "type": "string"
                },
                "portId": {
                    "description": "端口信息编码",
                    "type": "string"
                },
                "target": {
                    "description": "目标服务地址",
                    "type": "string"
                }
            }
        },
        "repository.CreateTarget": {
            "type": "object",
            "required": [
                "name"
            ],
            "properties": {
                "mark": {
                    "description": "备注",
                    "type": "string"
                },
                "name": {
                    "description": "目标地址",
                    "type": "string"
                }
            }
        },
        "repository.CreateUser": {
            "type": "object",
            "properties": {
                "account": {
                    "description": "uid 登录名",
                    "type": "string"
                },
                "mark": {
                    "description": "备注",
                    "type": "string"
                },
                "name": {
                    "description": "用户姓名",
                    "type": "string"
                },
                "password": {
                    "description": "密码",
                    "type": "string"
                }
            }
        },
        "repository.Login": {
            "type": "object",
            "properties": {
                "account": {
                    "description": "登录名",
                    "type": "string"
                },
                "password": {
                    "description": "密码",
                    "type": "string"
                }
            }
        },
        "repository.ModifyCert": {
            "type": "object",
            "required": [
                "id",
                "name",
                "private",
                "public"
            ],
            "properties": {
                "id": {
                    "description": "编码",
                    "type": "string"
                },
                "mark": {
                    "description": "备注",
                    "type": "string"
                },
                "name": {
                    "description": "名称",
                    "type": "string"
                },
                "private": {
                    "description": "私有证书路径",
                    "type": "string"
                },
                "public": {
                    "description": "公有证书路径",
                    "type": "string"
                }
            }
        },
        "repository.ModifyNode": {
            "type": "object",
            "required": [
                "id",
                "name",
                "portId",
                "target"
            ],
            "properties": {
                "id": {
                    "description": "编码",
                    "type": "string"
                },
                "mark": {
                    "description": "备注",
                    "type": "string"
                },
                "name": {
                    "description": "匹配路由名称",
                    "type": "string"
                },
                "nodeType": {
                    "description": "节点类型 0 api 1 页面",
                    "type": "integer"
                },
                "pagePath": {
                    "description": "静态页面存放路径 注：相对路径，由服务对页面进行管理",
                    "type": "string"
                },
                "portId": {
                    "description": "端口信息编码",
                    "type": "string"
                },
                "target": {
                    "description": "目标服务地址",
                    "type": "string"
                }
            }
        },
        "repository.ModifyPort": {
            "type": "object",
            "required": [
                "id",
                "port"
            ],
            "properties": {
                "certId": {
                    "description": "证书编码",
                    "type": "string"
                },
                "id": {
                    "description": "编码",
                    "type": "string"
                },
                "isTLS": {
                    "description": "是否证书加密",
                    "type": "boolean"
                },
                "mark": {
                    "description": "备注",
                    "type": "string"
                },
                "port": {
                    "description": "端口号",
                    "type": "integer"
                }
            }
        },
        "repository.ModifyRule": {
            "type": "object",
            "required": [
                "id",
                "matchType",
                "name",
                "portId",
                "target"
            ],
            "properties": {
                "id": {
                    "description": "编码",
                    "type": "string"
                },
                "mark": {
                    "description": "备注",
                    "type": "string"
                },
                "matchType": {
                    "description": "匹配模式 0 所有内容匹配 1 正则匹配 2 包含匹配 3 header 匹配",
                    "type": "integer"
                },
                "name": {
                    "description": "匹配路由名称",
                    "type": "string"
                },
                "nodeId": {
                    "description": "节点信息编码",
                    "type": "string"
                },
                "portId": {
                    "description": "端口信息编码",
                    "type": "string"
                },
                "target": {
                    "description": "目标服务地址",
                    "type": "string"
                }
            }
        },
        "repository.ModifyTarget": {
            "type": "object",
            "required": [
                "id",
                "name"
            ],
            "properties": {
                "id": {
                    "description": "编码",
                    "type": "string"
                },
                "mark": {
                    "description": "备注",
                    "type": "string"
                },
                "name": {
                    "description": "目标地址",
                    "type": "string"
                }
            }
        },
        "repository.ModifyUser": {
            "type": "object",
            "properties": {
                "account": {
                    "description": "uid 登录名",
                    "type": "string"
                },
                "id": {
                    "description": "编码",
                    "type": "integer"
                },
                "mark": {
                    "description": "备注",
                    "type": "string"
                },
                "name": {
                    "description": "用户姓名",
                    "type": "string"
                },
                "password": {
                    "description": "密码",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "V0.1",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "代理管理服务",
	Description:      "代理管理服务",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
